# Generated by Django 5.0.5 on 2024-05-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='name',
            field=models.CharField(default='hotel', max_length=30),
            preserve_default=False,
        ),
    ]
