# Generated by Django 5.0.6 on 2024-05-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_trip_available_alter_hotel_stars_alter_trip_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateField(default='2002-10-10'),
            preserve_default=False,
        ),
    ]
