# Generated by Django 5.0.5 on 2024-05-28 02:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_alter_user_address_alter_user_age_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieceofnews',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faq',
            name='added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='written',
            field=models.DateField(auto_now_add=True),
        ),
    ]
